---
title: "Engaging students with sports examples through SCORE"
format: gfm
---

> This page provides information and resources for the [USCOTS 2025 Breakout Session](https://www.causeweb.org/cause/uscots/uscots25/program/breakouts/4C){target="_blank"} on different strategies for using resources from NSF-funded Sports Content for Outreach, Research, and Education, [SCORE Network](https://scorenetwork.org){target="_blank"}, to engage students with sports-motivated statistics activities and data.

## Brief Outline

* What is SCORE?

* Level 1 - Instructor choice (SCORE modules)

* Level 2 - Student choice (SCORE Datasets)

* Level 3 - Student contributions (Review/Create SCORE materials)

## What is SCORE? 

<iframe width="560" height="315" src="https://www.youtube.com/embed/eBasNuOMTUs?si=ZUYhT4FSwc_7jUbQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

- SCORE Network website: [scorenetwork.org](https://scorenetwork.org){target="_blank"}  
  + For general information about the project (and links to all materials).

## Level 1 - Instructor Choice (Modules)

A SCORE module is a collection of teaching materials built around one or more sport-related dataset(s).

- Module Repository:
[modules.scorenetwork.org](https://modules.scorenetwork.org){target="_blank"} 
  + Links to existing modules, searchable by sport and statistical topic.
  + The [preprint servers](https://modules.scorenetwork.org/preprints.html){target="_blank"} also have a lot of additional modules to peruse.

### Three Examples

- [League of Legends - Buffing and Nerfing](https://modules.scorenetwork.org/esports/league-of-legends-buffing-nerfing/){target="_blank"}

- [NBA Wingspan & Performance](https://iramler.github.io/slu_score_preprints/basketball/nba_wingspans_and_performance/){target="_blank"}

- [Marathon Record-Setting Over Time](https://isle.stat.cmu.edu/SCORE/Marathons_SCORE_Template/){target="_blank"}

## Level 2 - Student Choice (Dataset Repository)

- Datasets Repository: [data.scorenetwork.org](https://data.scorenetwork.org){target="_blank"}  
  + Lots of example datasets that can be used to start the process of building a module.

ACTIVITY - TBD

## Level 3 - Student Contributions 

- Student reviews [Google form for Student Reviews](https://docs.google.com/forms/d/e/1FAIpQLSd7Sigx6d8h4RHu0EsybC4K6C1aUFL5t1AcpwlPj897eOtC9A/viewform){target="_blank"}
  + Have your students work through and then review a proposed SCORE module

- Submit a module, module idea, or dataset: 
[scorenetwork.org/submissions.html](https://scorenetwork.org/submissions.html){target="_blank"}
   + Instructions on how to submit materials to SCORE

### Useful links (Summary)

- SCORE Network website: [scorenetwork.org](https://scorenetwork.org){target="_blank"}  
  
- Module Repository:
[modules.scorenetwork.org](https://modules.scorenetwork.org){target="_blank"} 
  + Also [preprint servers](https://modules.scorenetwork.org/preprints.html){target="_blank"} for modules under review or in preparation.
  
  
- Datasets Repository: [data.scorenetwork.org](https://data.scorenetwork.org){target="_blank"}  


- Submit a module, module idea, or dataset: 
[scorenetwork.org/submissions.html](https://scorenetwork.org/submissions.html){target="_blank"}

- Link for student reviews: 
[Google form for Student Reviews](https://docs.google.com/forms/d/e/1FAIpQLSd7Sigx6d8h4RHu0EsybC4K6C1aUFL5t1AcpwlPj897eOtC9A/viewform){target="_blank"}




---
*Breakout leads: Robin Lock (St. Lawrence University), Ivan Ramler (St. Lawrence University), Nick Clark (St. Thomas University),  Michael Schuckers (University of North Carolina - Charlotte)*
